Module molVCT_TYPE
    Structure STR_ThangBo_CONFIG
        Dim EL1 As Decimal
        Dim EL2 As Decimal
        Dim EL3 As Decimal
        Dim Lx As Decimal
        Dim L2 As Decimal
        Dim L3 As Decimal
        Dim L4 As Decimal
        Dim H1 As Decimal
        Dim H2 As Decimal
        Dim T1 As Decimal
        Dim T2 As Decimal
        Dim T3 As Decimal
        Dim T4 As Decimal
        Dim T5 As Decimal
        Dim a As Decimal
        Dim IsHave_L3 As Boolean
        Dim cboMB_CanhTrai As String
        Dim cboMB_CanhPhai As String
        Dim cboDinhThang As String
        Dim cboDamDinh As String
        Dim cboDamDinh2 As String
        Dim cboDamChan As String
        Dim xBb1 As Decimal
        Dim xHb1 As Decimal
        Dim xDx1 As Decimal
        Dim xBb2 As Decimal
        Dim xHb2 As Decimal
        Dim xDx2 As Decimal
        Dim Bb1 As Decimal
        Dim Hb1 As Decimal
        Dim Dx1 As Decimal
        Dim Bb2 As Decimal
        Dim Hb2 As Decimal
        Dim Dx2 As Decimal
        Dim Bb3 As Decimal
        Dim Hb3 As Decimal
        Dim Dx3 As Decimal
        Dim Bb4 As Decimal
        Dim Hb4 As Decimal
        Dim Dx4 As Decimal
        Dim Bar1_X_Bot As STR_CONFIG_BAR
        Dim Bar1_X_Top As STR_CONFIG_BAR
        Dim IsHave_Bar1_X_Top As Boolean
        Dim cboBar1_X_Top As String
        Dim Bar1_Y_Bot As STR_CONFIG_BAR
        Dim Bar1_Y_Top As STR_CONFIG_BAR
        Dim IsHave_Bar1_Y_Top As Boolean
        Dim cboBar1_Y_Top As String
        Dim Bar2_X_Bot As STR_CONFIG_BAR
        Dim Bar2_X_Top As STR_CONFIG_BAR
        Dim IsHave_Bar2_X_Top As Boolean
        Dim cboBar2_X_Top As String
        Dim Bar2_Y_Bot As STR_CONFIG_BAR
        Dim Bar2_Y_Top As STR_CONFIG_BAR
        Dim IsHave_Bar2_Y_Top As Boolean
        Dim cboBar2_Y_Top As String
        Dim Bar3_X_Bot As STR_CONFIG_BAR
        Dim Bar3_X_Top As STR_CONFIG_BAR
        Dim IsHave_Bar3_X_Top As Boolean
        Dim cboBar3_X_Top As String
        Dim Bar3_Y_Bot As STR_CONFIG_BAR
        Dim Bar3_Y_Top As STR_CONFIG_BAR
        Dim IsHave_Bar3_Y_Top As Boolean
        Dim cboBar3_Y_Top As String
        Dim Bar_cautao As STR_CONFIG_BAR
    End Structure
End Module
